version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
#    volumes:
#     - postgres_data:/var/lib/postgresql/data
#     - ./custom_postgres.conf:/etc/postgresql/postgres.conf # Mount custom config
    command:
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"
volumes:
  postgres_data:
